### ISSUE TITLE
 Request to Add README to Repository

### ISSUE THREAD

**Issue by nihalpawar4** [rohit2k3/telegram-bard-chatBot#1]
I'd like to suggest adding a README file to the repository as it would help provide essential information about the project's purpose, setup, usage, and how others can contribute.

**Comment by rohit2k3** [comment]
**Issue #1:** Adding a README file to the repository

Hello nihalpawar4,

Thank you for your suggestion! I have added a README file to the repository with essential information about the project's purpose, setup, usage, and how others can contribute. Feel free to check it out and let us know if you have any further feedback.

Best regards,
Rohit

**Comment by rohit2k3** [comment]
**Issue #1:** Adding a README file to the repository

Hello nihalpawar4,

Thank you for your suggestion! I have added a README file to the repository with essential information about the project's purpose, setup, usage, and how others can contribute. Feel free to check it out and let us know if you have any further feedback.

Best regards,
Rohit
